name: Build and Test

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libevent-dev libssl-dev libnet1-dev libpcap-dev libsqlite3-dev check

    - name: Build
      run: make

    - name: Run unit tests
      run: make unittest

    - name: Print version
      run: src/sslproxy -V
